spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_account?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wang1024!

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: demo-ddd-main
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://localhost:2181
