// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.google.protocol;

public final class UserProtobuf {
  private UserProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010protocol\"\242\001\n\004User\022\016\n\006us" +
      "erId\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\017\n\005error\030\003 " +
      "\001(\tH\000\022\016\n\004code\030\004 \001(\005H\000\022\014\n\004name\030\010 \001(\t\022$\n\010u" +
      "serType\030\t \001(\0162\022.protocol.UserType\022\r\n\005rol" +
      "es\030\n \003(\005B\005\n\003msgJ\004\010\006\020\010R\007userId2*4\n\010UserTy" +
      "pe\022\n\n\006UNKNOW\020\000\022\t\n\005ADMIN\020\001\022\021\n\rBUSINESS_US" +
      "ER\020\0022\233\001\n\013UserService\022+\n\007getUser\022\016.protoc" +
      "ol.User\032\016.protocol.User\"\000\022.\n\010getUsers\022\016." +
      "protocol.User\032\016.protocol.User\"\0000\001\022/\n\tsav" +
      "eUsers\022\016.protocol.User\032\016.protocol.User\"\000" +
      "(\001B/\n\023com.google.protocolB\014UserProtobufP" +
      "\001Z\010protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_User_descriptor,
        new java.lang.String[] { "UserId", "Username", "Error", "Code", "Name", "UserType", "Roles", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
