// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skuListRes.proto

package org.example.protocol;

public interface GetSkuListResDTOProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protocol.GetSkuListResDTOProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 companyId = 1;</code>
   */
  long getCompanyId();

  /**
   * <code>int32 saleC1Id = 2;</code>
   */
  int getSaleC1Id();

  /**
   * <code>int64 biId = 3;</code>
   */
  long getBiId();

  /**
   * <code>int64 skuId = 4;</code>
   */
  long getSkuId();

  /**
   * <pre>
   * 来源 0:商户添加 1:下单写入
   * </pre>
   *
   * <code>int32 source = 5;</code>
   */
  int getSource();

  /**
   * <pre>
   * 注意：Java中的Integer类型在protobuf中通常对应int32，但如果你明确这是用来表示时间戳且可能为null，
   * 在protobuf中没有直接的null支持，通常我们会用特殊值（如0或负数）来表示"未设置"状态。
   * 这里假设lastOrderTime和channel非负，如果可以为负，请调整或者明确其含义。
   * </pre>
   *
   * <code>int32 lastOrderTime = 6;</code>
   */
  int getLastOrderTime();

  /**
   * <code>int32 channel = 7;</code>
   */
  int getChannel();

  /**
   * <code>int32 buyNum = 8;</code>
   */
  int getBuyNum();

  /**
   * <code>int64 uT = 9;</code>
   */
  long getUT();
}
