// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skuListRes.proto

package org.example.protocol;

public final class SkuListRes {
  private SkuListRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protocol_GetSkuListResDTOProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protocol_GetSkuListResDTOProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020skuListRes.proto\022\014com.protocol\"\255\001\n\025Get" +
      "SkuListResDTOProto\022\021\n\tcompanyId\030\001 \001(\003\022\020\n" +
      "\010saleC1Id\030\002 \001(\005\022\014\n\004biId\030\003 \001(\003\022\r\n\005skuId\030\004" +
      " \001(\003\022\016\n\006source\030\005 \001(\005\022\025\n\rlastOrderTime\030\006 " +
      "\001(\005\022\017\n\007channel\030\007 \001(\005\022\016\n\006buyNum\030\010 \001(\005\022\n\n\002" +
      "uT\030\t \001(\003B\030\n\024org.example.protocolP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protocol_GetSkuListResDTOProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protocol_GetSkuListResDTOProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protocol_GetSkuListResDTOProto_descriptor,
        new java.lang.String[] { "CompanyId", "SaleC1Id", "BiId", "SkuId", "Source", "LastOrderTime", "Channel", "BuyNum", "UT", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
