
spring:
  kafka:
    bootstrap-servers: localhost:9094,localhost:9095
    producer:
      acks: 1
      batch-size: 16384
      retries: 2
      buffer-memory: 33554432
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer.class
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer.class
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 1S
      auto-offset-reset: earliest
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer.class
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer.class
      group-id: myConsumerGroup
    listener:
      ack-mode: manual_immediate
      concurrency: 5
      missing-topics-fatal: false
server:
  port: 8888